version: "3.9"
services:
  # broker with loadbalancer
  mosquitto1:
    image: eclipse-mosquitto:latest
    ports:
      - "2883:1883"
      - "9002:9001"
    volumes:
      - ./mosquitto1/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt-loadbalancer:
        ipv4_address: 10.10.0.7
  mosquitto2:
    image: eclipse-mosquitto:latest
    ports:
      - "3883:1883"
      - "9003:9001"
    volumes:
      - ./mosquitto2/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt-loadbalancer:
        ipv4_address: 10.10.0.8
  # publiser
  pub1:
    build: "./mqtt-publisher/"
    environment:
      - CLIENT=container1
    networks:
      mqtt-loadbalancer:
        ipv4_address: 10.10.0.9
  pub2:
    build: "./mqtt-publisher/"
    environment:
      - CLIENT=container2
    networks:
      mqtt-loadbalancer:
        ipv4_address: 10.10.0.10

  lb_broker:
    image: nginx:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./nginx-tcp/nginx.conf:/etc/nginx/nginx.conf
    networks:
      mqtt-loadbalancer:
        ipv4_address: 10.10.0.12

networks:
  # loadbalancer:
  #   driver: bridge
  #   ipam:
  #    config:
  #      - subnet: 10.0.0.0/8
  #        gateway: 10.0.0.1
  mqtt-loadbalancer:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/8
          gateway: 10.10.0.1
